#!/usr/bin/env python3
"""
export_obm_spent_value_age_band_btc_daily.py

Export the Open Bitcoin Metrics daily spent-output value by age band:

    obm_spent_value_age_band_btc_daily

from the persistent SQLite database generated by:

    obm_spent_output_indexer.py

This exporter writes a wide daily table: one row per UTC date and one column
per age band.

Output schema:

    date,
    series_id,
    spent_value_0d_1d_btc,
    spent_value_1d_1w_btc,
    spent_value_1w_1m_btc,
    spent_value_1m_3m_btc,
    spent_value_3m_6m_btc,
    spent_value_6m_1y_btc,
    spent_value_1y_2y_btc,
    spent_value_2y_3y_btc,
    spent_value_3y_5y_btc,
    spent_value_5y_7y_btc,
    spent_value_7y_10y_btc,
    spent_value_10y_plus_btc,
    unit,
    frequency,
    release_version

Definition:

    For each UTC day d and age band k,

        SpentValueAgeBandBTC_{d,k}

    is the BTC value of outputs spent on day d whose age at spending belongs
    to band k.

Important convention:
    If a date has no row for a given age band, the exporter writes zero for
    that age-band column. This is appropriate because each age-band value is
    a daily flow variable.
"""

from __future__ import annotations

import argparse
import csv
import sqlite3
import sys
from datetime import date, datetime, timedelta
from decimal import Decimal, getcontext
from pathlib import Path
from typing import Dict, List, Optional


SERIES_ID = "obm_spent_value_age_band_btc_daily"
UNIT = "BTC"
FREQUENCY = "daily"
DEFAULT_RELEASE_VERSION = "OBM v0.1.0"

EXPECTED_INDEXER_ID = "obm_spent_output_indexer"

SATOSHIS_PER_BTC = Decimal("100000000")

getcontext().prec = 50


# ---------------------------------------------------------------------
# Age-band convention
# ---------------------------------------------------------------------

# These labels must match the labels stored by obm_spent_output_indexer.py
# in daily_age_band_aggregates.age_band.
AGE_BANDS = [
    "0d_1d",
    "1d_1w",
    "1w_1m",
    "1m_3m",
    "3m_6m",
    "6m_1y",
    "1y_2y",
    "2y_3y",
    "3y_5y",
    "5y_7y",
    "7y_10y",
    "10y_plus",
]

AGE_BAND_OUTPUT_COLUMNS = {
    "0d_1d": "spent_value_0d_1d_btc",
    "1d_1w": "spent_value_1d_1w_btc",
    "1w_1m": "spent_value_1w_1m_btc",
    "1m_3m": "spent_value_1m_3m_btc",
    "3m_6m": "spent_value_3m_6m_btc",
    "6m_1y": "spent_value_6m_1y_btc",
    "1y_2y": "spent_value_1y_2y_btc",
    "2y_3y": "spent_value_2y_3y_btc",
    "3y_5y": "spent_value_3y_5y_btc",
    "5y_7y": "spent_value_5y_7y_btc",
    "7y_10y": "spent_value_7y_10y_btc",
    "10y_plus": "spent_value_10y_plus_btc",
}


# ---------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------

def parse_utc_date(value: str) -> date:
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"Invalid date '{value}'. Expected format: YYYY-MM-DD."
        ) from exc


def daterange(start: date, end: date) -> List[date]:
    days: List[date] = []
    current = start

    while current <= end:
        days.append(current)
        current += timedelta(days=1)

    return days


# ---------------------------------------------------------------------
# SQLite helpers
# ---------------------------------------------------------------------

def connect_state_db(db_path: Path) -> sqlite3.Connection:
    if not db_path.exists():
        raise FileNotFoundError(f"State database not found: {db_path}")

    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA query_only=ON;")
    return conn


def get_metadata(conn: sqlite3.Connection, key: str) -> Optional[str]:
    row = conn.execute(
        "SELECT value FROM metadata WHERE key = ?;",
        (key,),
    ).fetchone()

    if row is None:
        return None

    return str(row[0])


def table_exists(conn: sqlite3.Connection, table_name: str) -> bool:
    row = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table' AND name = ?;
        """,
        (table_name,),
    ).fetchone()

    return row is not None


def get_table_columns(conn: sqlite3.Connection, table_name: str) -> List[str]:
    rows = conn.execute(f"PRAGMA table_info({table_name});").fetchall()
    return [str(row[1]) for row in rows]


def validate_indexer_database(conn: sqlite3.Connection) -> None:
    indexer_id = get_metadata(conn, "indexer_id")

    if indexer_id != EXPECTED_INDEXER_ID:
        raise RuntimeError(
            f"Unexpected indexer_id in state database: {indexer_id}. "
            f"Expected {EXPECTED_INDEXER_ID}."
        )

    last_processed_height = get_metadata(conn, "last_processed_height")
    last_processed_date = get_metadata(conn, "last_processed_date")
    max_processed_date = get_metadata(conn, "max_processed_date")

    if last_processed_height is None:
        raise RuntimeError(
            "The state database does not contain last_processed_height. "
            "It appears that the indexer has not processed any blocks yet."
        )

    if last_processed_date is None or max_processed_date is None:
        raise RuntimeError(
            "The state database does not contain processed-date metadata. "
            "It appears incomplete."
        )

    if not table_exists(conn, "daily_age_band_aggregates"):
        raise RuntimeError(
            "The state database does not contain the daily_age_band_aggregates table."
        )

    required_columns = {"date", "age_band", "spent_value_sats"}
    columns = set(get_table_columns(conn, "daily_age_band_aggregates"))
    missing = required_columns - columns

    if missing:
        raise RuntimeError(
            "The daily_age_band_aggregates table is missing required columns: "
            + ", ".join(sorted(missing))
        )


def infer_release_version(conn: sqlite3.Connection, fallback: str) -> str:
    release_version = get_metadata(conn, "release_version")
    return release_version if release_version is not None else fallback


def ensure_requested_range_available(
    conn: sqlite3.Connection,
    end_date: date,
) -> None:
    max_processed_date_raw = get_metadata(conn, "max_processed_date")

    if max_processed_date_raw is None:
        raise RuntimeError(
            "Cannot determine max_processed_date from the indexer database."
        )

    max_processed_date = parse_utc_date(max_processed_date_raw)

    if end_date > max_processed_date:
        raise ValueError(
            f"Requested end_date {end_date.isoformat()} is beyond the "
            f"maximum processed date in the indexer database "
            f"({max_processed_date.isoformat()}). Run the indexer further first."
        )


# ---------------------------------------------------------------------
# Metric extraction
# ---------------------------------------------------------------------

def read_spent_value_age_band_btc(
    conn: sqlite3.Connection,
    start_date: date,
    end_date: date,
) -> Dict[date, Dict[str, Decimal]]:
    """
    Read daily spent value by age band and convert satoshis to BTC.

    Missing date-band pairs are exported as zero. This is appropriate because
    each band is a daily flow variable.
    """
    output: Dict[date, Dict[str, Decimal]] = {}

    for d in daterange(start_date, end_date):
        output[d] = {band: Decimal("0") for band in AGE_BANDS}

    rows = conn.execute(
        """
        SELECT date, age_band, spent_value_sats
        FROM daily_age_band_aggregates
        WHERE date >= ? AND date <= ?;
        """,
        (start_date.isoformat(), end_date.isoformat()),
    ).fetchall()

    expected_bands = set(AGE_BANDS)

    for row in rows:
        raw_date = str(row[0])
        age_band = str(row[1])
        spent_value_sats = Decimal(str(row[2]))

        if age_band not in expected_bands:
            raise RuntimeError(
                f"Unexpected age_band found in indexer database: {age_band!r}. "
                f"Expected one of: {', '.join(AGE_BANDS)}."
            )

        d = parse_utc_date(raw_date)

        if d not in output:
            # Should not happen because of the SQL WHERE clause, but keep this
            # as a defensive check.
            continue

        if output[d][age_band] != 0:
            raise RuntimeError(
                f"Duplicate age-band aggregate found for date={raw_date}, "
                f"age_band={age_band}."
            )

        if spent_value_sats < 0:
            raise RuntimeError(
                f"Negative spent_value_sats found for date={raw_date}, "
                f"age_band={age_band}: {spent_value_sats}."
            )

        output[d][age_band] = spent_value_sats / SATOSHIS_PER_BTC

    return output


# ---------------------------------------------------------------------
# CSV output
# ---------------------------------------------------------------------

def build_fieldnames() -> List[str]:
    return (
        ["date", "series_id"]
        + [AGE_BAND_OUTPUT_COLUMNS[band] for band in AGE_BANDS]
        + ["unit", "frequency", "release_version"]
    )


def write_obm_csv(
    output_path: Path,
    values_by_date: Dict[date, Dict[str, Decimal]],
    release_version: str,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = build_fieldnames()

    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for d in sorted(values_by_date):
            row = {
                "date": d.isoformat(),
                "series_id": SERIES_ID,
                "unit": UNIT,
                "frequency": FREQUENCY,
                "release_version": release_version,
            }

            for band in AGE_BANDS:
                col = AGE_BAND_OUTPUT_COLUMNS[band]
                row[col] = f"{values_by_date[d][band]:.8f}"

            writer.writerow(row)


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------

def plot_obm_series(
    values_by_date: Dict[date, Dict[str, Decimal]],
    output_path: Path,
) -> None:
    """
    Generate a simple line plot of total spent value across all age bands.

    The CSV itself contains the age-band decomposition. The default plot shows
    the row sum, because plotting all bands in one figure can be visually noisy.
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError(
            "The --plot flag requires matplotlib. Install it with: "
            "python3 -m pip install matplotlib"
        ) from exc

    dates = sorted(values_by_date)
    totals = [
        float(sum(values_by_date[d][band] for band in AGE_BANDS))
        for d in dates
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(11, 5.5))
    ax.plot(dates, totals)

    start = min(dates).isoformat()
    end = max(dates).isoformat()

    ax.set_title(
        f"Open Bitcoin Metrics: Total Spent Value Across Age Bands "
        f"({start} to {end})"
    )
    ax.set_xlabel("Date")
    ax.set_ylabel("BTC")
    ax.grid(True, alpha=0.3)

    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------
# Optional validation helper
# ---------------------------------------------------------------------

def validate_row_sums_against_daily_aggregates(
    conn: sqlite3.Connection,
    values_by_date: Dict[date, Dict[str, Decimal]],
    tolerance_btc: Decimal,
) -> None:
    """
    If daily_aggregates is present with spent_value_sats, verify that the sum
    across age-band columns equals total spent value for each date.

    This validation is useful because both tables should be generated by the
    same indexer pass.
    """
    if not table_exists(conn, "daily_aggregates"):
        return

    columns = set(get_table_columns(conn, "daily_aggregates"))
    if not {"date", "spent_value_sats"}.issubset(columns):
        return

    for d in sorted(values_by_date):
        row = conn.execute(
            """
            SELECT spent_value_sats
            FROM daily_aggregates
            WHERE date = ?;
            """,
            (d.isoformat(),),
        ).fetchone()

        if row is None:
            expected_total_btc = Decimal("0")
        else:
            expected_total_btc = Decimal(str(row[0])) / SATOSHIS_PER_BTC

        band_total_btc = sum(values_by_date[d][band] for band in AGE_BANDS)
        diff = abs(band_total_btc - expected_total_btc)

        if diff > tolerance_btc:
            raise RuntimeError(
                f"Age-band row sum does not match total spent value on {d}: "
                f"age_band_sum={band_total_btc}, "
                f"daily_aggregates_spent_value={expected_total_btc}, "
                f"diff={diff}, tolerance={tolerance_btc}."
            )


# ---------------------------------------------------------------------
# Command-line interface
# ---------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Export obm_spent_value_age_band_btc_daily from the persistent "
            "OBM spent-output indexer database."
        )
    )

    parser.add_argument(
        "--start_date",
        required=True,
        type=parse_utc_date,
        help="Start date, inclusive, in YYYY-MM-DD format.",
    )

    parser.add_argument(
        "--end_date",
        required=True,
        type=parse_utc_date,
        help="End date, inclusive, in YYYY-MM-DD format.",
    )

    parser.add_argument(
        "--state_db",
        default="cache/obm_spent_output_indexer.sqlite",
        help=(
            "Path to the persistent SQLite database generated by "
            "obm_spent_output_indexer.py. "
            "Default: cache/obm_spent_output_indexer.sqlite."
        ),
    )

    parser.add_argument(
        "--output",
        default="obm_spent_value_age_band_btc_daily.csv",
        help="Output CSV file path.",
    )

    parser.add_argument(
        "--release_version",
        default=DEFAULT_RELEASE_VERSION,
        help=(
            "Dataset release version. If the indexer database contains "
            "release_version metadata, that value is used instead. "
            f"Default fallback: {DEFAULT_RELEASE_VERSION}."
        ),
    )

    parser.add_argument(
        "--validate_row_sums",
        action="store_true",
        help=(
            "Validate that the sum across age-band columns equals "
            "daily_aggregates.spent_value_sats for each date, when available."
        ),
    )

    parser.add_argument(
        "--row_sum_tolerance",
        default=Decimal("0.00000001"),
        type=Decimal,
        help=(
            "Tolerance in BTC for --validate_row_sums. "
            "Default: 0.00000001."
        ),
    )

    parser.add_argument(
        "--plot",
        action="store_true",
        help=(
            "Generate a plot of the total spent value obtained by summing "
            "all age-band columns."
        ),
    )

    parser.add_argument(
        "--plot_output",
        default=None,
        help=(
            "Output path for the plot. If omitted and --plot is used, "
            "the plot is saved next to the CSV file with .png extension."
        ),
    )

    return parser


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()

    try:
        if args.start_date > args.end_date:
            raise ValueError("--start_date must be earlier than or equal to --end_date.")

        state_db_path = Path(args.state_db)
        conn = connect_state_db(state_db_path)

        try:
            validate_indexer_database(conn)

            ensure_requested_range_available(
                conn=conn,
                end_date=args.end_date,
            )

            release_version = infer_release_version(
                conn=conn,
                fallback=args.release_version,
            )

            values_by_date = read_spent_value_age_band_btc(
                conn=conn,
                start_date=args.start_date,
                end_date=args.end_date,
            )

            if args.validate_row_sums:
                validate_row_sums_against_daily_aggregates(
                    conn=conn,
                    values_by_date=values_by_date,
                    tolerance_btc=args.row_sum_tolerance,
                )

        finally:
            conn.close()

        output_path = Path(args.output)

        write_obm_csv(
            output_path=output_path,
            values_by_date=values_by_date,
            release_version=release_version,
        )

        print(
            f"Wrote {len(values_by_date)} daily observations to {output_path}",
            file=sys.stderr,
        )

        if args.plot:
            if args.plot_output is not None:
                plot_output_path = Path(args.plot_output)
            else:
                plot_output_path = output_path.with_suffix(".png")

            plot_obm_series(
                values_by_date=values_by_date,
                output_path=plot_output_path,
            )

            print(f"Wrote plot to {plot_output_path}", file=sys.stderr)

        return 0

    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
