#!/usr/bin/env python3
"""
compute_obm_cdd_btcxdays_daily.py

Export the Open Bitcoin Metrics daily Bitcoin Days Destroyed series:

    obm_cdd_btcxdays_daily

from the persistent SQLite database generated by:

    obm_spent_output_indexer.py

The script does not query Bitcoin Core. It simply reads the daily aggregate
table produced by the spent-output indexer and writes a standard OBM CSV file.

Output schema:

    date,series_id,value,unit,frequency,release_version

Example:

    python3 compute_obm_cdd_btcxdays_daily.py \
        --start_date 2024-01-01 \
        --end_date 2024-01-31 \
        --state_db cache/obm_spent_output_indexer.sqlite \
        --output data/daily/obm_cdd_btcxdays_daily.csv

Definition:

    obm_cdd_btcxdays_daily reports the total BTC-days destroyed by outputs
    spent in blocks assigned to each UTC calendar day.

    The indexer stores CDD internally as satoshi-days:

        cdd_sats_days = sum(value_sats * age_days)

    This exporter converts satoshi-days to BTC-days:

        cdd_btc_days = cdd_sats_days / 100,000,000
"""

from __future__ import annotations

import argparse
import csv
import sqlite3
import sys
from datetime import date, datetime, timedelta
from decimal import Decimal, getcontext
from pathlib import Path
from typing import Dict, List, Optional


SERIES_ID = "obm_cdd_btcxdays_daily"
UNIT = "BTC-days"
FREQUENCY = "daily"
DEFAULT_RELEASE_VERSION = "OBM v0.1.0"

EXPECTED_INDEXER_ID = "obm_spent_output_indexer"

SATOSHIS_PER_BTC = Decimal("100000000")

getcontext().prec = 50


# ---------------------------------------------------------------------
# Date helpers
# ---------------------------------------------------------------------

def parse_utc_date(value: str) -> date:
    try:
        return datetime.strptime(value, "%Y-%m-%d").date()
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"Invalid date '{value}'. Expected format: YYYY-MM-DD."
        ) from exc


def daterange(start: date, end: date) -> List[date]:
    days: List[date] = []
    current = start

    while current <= end:
        days.append(current)
        current += timedelta(days=1)

    return days


# ---------------------------------------------------------------------
# SQLite helpers
# ---------------------------------------------------------------------

def connect_state_db(db_path: Path) -> sqlite3.Connection:
    if not db_path.exists():
        raise FileNotFoundError(f"State database not found: {db_path}")

    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA query_only=ON;")

    return conn


def get_metadata(conn: sqlite3.Connection, key: str) -> Optional[str]:
    row = conn.execute(
        "SELECT value FROM metadata WHERE key = ?;",
        (key,),
    ).fetchone()

    if row is None:
        return None

    return str(row[0])


def validate_indexer_database(conn: sqlite3.Connection) -> None:
    indexer_id = get_metadata(conn, "indexer_id")

    if indexer_id != EXPECTED_INDEXER_ID:
        raise RuntimeError(
            f"Unexpected indexer_id in state database: {indexer_id}. "
            f"Expected {EXPECTED_INDEXER_ID}."
        )

    last_processed_height = get_metadata(conn, "last_processed_height")
    last_processed_date = get_metadata(conn, "last_processed_date")
    max_processed_date = get_metadata(conn, "max_processed_date")

    if last_processed_height is None:
        raise RuntimeError(
            "The state database does not contain last_processed_height. "
            "It appears that the indexer has not processed any blocks yet."
        )

    if last_processed_date is None or max_processed_date is None:
        raise RuntimeError(
            "The state database does not contain processed-date metadata. "
            "It appears incomplete."
        )


def infer_release_version(conn: sqlite3.Connection, fallback: str) -> str:
    release_version = get_metadata(conn, "release_version")
    return release_version if release_version is not None else fallback


def ensure_requested_range_available(
    conn: sqlite3.Connection,
    start_date: date,
    end_date: date,
) -> None:
    max_processed_date_raw = get_metadata(conn, "max_processed_date")

    if max_processed_date_raw is None:
        raise RuntimeError(
            "Cannot determine max_processed_date from the indexer database."
        )

    max_processed_date = parse_utc_date(max_processed_date_raw)

    if end_date > max_processed_date:
        raise ValueError(
            f"Requested end_date {end_date.isoformat()} is beyond the "
            f"maximum processed date in the indexer database "
            f"({max_processed_date.isoformat()}). Run the indexer further first."
        )

    first_row = conn.execute(
        "SELECT MIN(date) FROM daily_aggregates;"
    ).fetchone()

    if first_row is None or first_row[0] is None:
        raise RuntimeError("The daily_aggregates table is empty.")

    first_available_date = parse_utc_date(str(first_row[0]))

    if start_date < first_available_date:
        raise ValueError(
            f"Requested start_date {start_date.isoformat()} is before the "
            f"first available aggregate date ({first_available_date.isoformat()})."
        )


# ---------------------------------------------------------------------
# Metric extraction
# ---------------------------------------------------------------------

def read_cdd_btc_days(
    conn: sqlite3.Connection,
    start_date: date,
    end_date: date,
    strict: bool,
) -> Dict[date, Optional[Decimal]]:
    """
    Read daily CDD from daily_aggregates and convert satoshi-days to BTC-days.

    If strict is True, all dates in the interval must exist in daily_aggregates.
    If strict is False, missing dates are exported as zero.
    """
    output: Dict[date, Optional[Decimal]] = {}

    for d in daterange(start_date, end_date):
        row = conn.execute(
            """
            SELECT cdd_sats_days
            FROM daily_aggregates
            WHERE date = ?;
            """,
            (d.isoformat(),),
        ).fetchone()

        if row is None:
            if strict:
                raise ValueError(
                    f"Missing daily_aggregates row for date {d.isoformat()}."
                )
            output[d] = Decimal("0")
            continue

        cdd_sats_days = Decimal(str(row[0]))
        cdd_btc_days = cdd_sats_days / SATOSHIS_PER_BTC
        output[d] = cdd_btc_days

    return output


# ---------------------------------------------------------------------
# CSV output
# ---------------------------------------------------------------------

def write_obm_csv(
    output_path: Path,
    cdd_by_date: Dict[date, Optional[Decimal]],
    release_version: str,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "date",
        "series_id",
        "value",
        "unit",
        "frequency",
        "release_version",
    ]

    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for d in sorted(cdd_by_date):
            value = cdd_by_date[d]

            writer.writerow(
                {
                    "date": d.isoformat(),
                    "series_id": SERIES_ID,
                    "value": "" if value is None else f"{value:.8f}",
                    "unit": UNIT,
                    "frequency": FREQUENCY,
                    "release_version": release_version,
                }
            )


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------

def plot_obm_series(
    cdd_by_date: Dict[date, Optional[Decimal]],
    output_path: Path,
) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError(
            "The --plot flag requires matplotlib. Install it with: "
            "python3 -m pip install matplotlib"
        ) from exc

    dates = [
        d for d in sorted(cdd_by_date)
        if cdd_by_date[d] is not None
    ]
    values = [float(cdd_by_date[d]) for d in dates]

    if not dates:
        raise ValueError("No defined CDD values are available to plot.")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(11, 5.5))
    ax.plot(dates, values)

    start = min(cdd_by_date).isoformat()
    end = max(cdd_by_date).isoformat()

    ax.set_title(
        f"Open Bitcoin Metrics: Bitcoin Days Destroyed "
        f"({start} to {end})"
    )
    ax.set_xlabel("Date")
    ax.set_ylabel("BTC-days")
    ax.grid(True, alpha=0.3)

    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------
# Command-line interface
# ---------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Export obm_cdd_btcxdays_daily from the persistent "
            "OBM spent-output indexer database."
        )
    )

    parser.add_argument(
        "--start_date",
        required=True,
        type=parse_utc_date,
        help="Start date, inclusive, in YYYY-MM-DD format.",
    )

    parser.add_argument(
        "--end_date",
        required=True,
        type=parse_utc_date,
        help="End date, inclusive, in YYYY-MM-DD format.",
    )

    parser.add_argument(
        "--state_db",
        default="cache/obm_spent_output_indexer.sqlite",
        help=(
            "Path to the persistent SQLite database generated by "
            "obm_spent_output_indexer.py. "
            "Default: cache/obm_spent_output_indexer.sqlite."
        ),
    )

    parser.add_argument(
        "--output",
        default="obm_cdd_btcxdays_daily.csv",
        help="Output CSV file path.",
    )

    parser.add_argument(
        "--release_version",
        default=DEFAULT_RELEASE_VERSION,
        help=(
            "Dataset release version. If the indexer database contains "
            "release_version metadata, that value is used instead. "
            f"Default fallback: {DEFAULT_RELEASE_VERSION}."
        ),
    )

    parser.add_argument(
        "--allow_missing_dates",
        action="store_true",
        help=(
            "Allow missing dates in daily_aggregates and export them as zero. "
            "By default, the script requires all requested dates to exist."
        ),
    )

    parser.add_argument(
        "--plot",
        action="store_true",
        help="Generate a plot of the exported series.",
    )

    parser.add_argument(
        "--plot_output",
        default=None,
        help=(
            "Output path for the plot. If omitted and --plot is used, "
            "the plot is saved next to the CSV file with .png extension."
        ),
    )

    return parser


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()

    try:
        if args.start_date > args.end_date:
            raise ValueError("--start_date must be earlier than or equal to --end_date.")

        state_db_path = Path(args.state_db)
        conn = connect_state_db(state_db_path)

        try:
            validate_indexer_database(conn)

            ensure_requested_range_available(
                conn=conn,
                start_date=args.start_date,
                end_date=args.end_date,
            )

            release_version = infer_release_version(
                conn=conn,
                fallback=args.release_version,
            )

            cdd_by_date = read_cdd_btc_days(
                conn=conn,
                start_date=args.start_date,
                end_date=args.end_date,
                strict=not args.allow_missing_dates,
            )

        finally:
            conn.close()

        output_path = Path(args.output)

        write_obm_csv(
            output_path=output_path,
            cdd_by_date=cdd_by_date,
            release_version=release_version,
        )

        print(
            f"Wrote {len(cdd_by_date)} daily observations to {output_path}",
            file=sys.stderr,
        )

        if args.plot:
            if args.plot_output is not None:
                plot_output_path = Path(args.plot_output)
            else:
                plot_output_path = output_path.with_suffix(".png")

            plot_obm_series(
                cdd_by_date=cdd_by_date,
                output_path=plot_output_path,
            )

            print(f"Wrote plot to {plot_output_path}", file=sys.stderr)

        return 0

    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
